### ISSUE TITLE
Unhandled error in Deferred | TypeError: Cannot create a consistent method resolution

### ISSUE THREAD

**Issue by diego-alfadev** [zytedata/zyte-autoextract#42]
Hello there, im having an issue with the autoextract package. I'm not able to get my script to pull up and start working.

My project is a news scraping tool that uses zyte automatic extraction API to scrape articles given some URLs.
It's built following the scrapy project guidelines, i have my so called 'googlenews' spider that performs the task i described before.

Since 08/05/2023, my script stopped working without me making any change to the source code.
Just when the program is starting i get the following error trace:

```
Unhandled error in Deferred:
2023-08-07 04:00:05 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/scrapy/crawler.py", line 245, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/scrapy/crawler.py", line 249, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1947, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1857, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/usr/local/lib/python3.11/site-packages/scrapy/crawler.py", line 134, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.11/site-packages/scrapy/crawler.py", line 148, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.11/site-packages/scrapy/core/engine.py", line 98, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
  File "/usr/local/lib/python3.11/site-packages/scrapy/core/downloader/__init__.py", line 97, in __init__
    DownloaderMiddlewareManager.from_crawler(crawler)
  File "/usr/local/lib/python3.11/site-packages/scrapy/middleware.py", line 67, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.11/site-packages/scrapy/middleware.py", line 43, in from_settings
    mwcls = load_object(clspath)
  File "/usr/local/lib/python3.11/site-packages/scrapy/utils/misc.py", line 79, in load_object
    mod = import_module(module)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
    
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
    
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    
  File "/usr/local/lib/python3.11/site-packages/scrapy_autoextract/__init__.py", line 2, in <module>
    from .providers import AutoExtractProvider  # noqa: F401
  File "/usr/local/lib/python3.11/site-packages/scrapy_autoextract/providers.py", line 17, in <module>
    from autoextract_poet.page_inputs import (
  File "/usr/local/lib/python3.11/site-packages/autoextract_poet/__init__.py", line 2, in <module>
    from .pages import *
  File "/usr/local/lib/python3.11/site-packages/autoextract_poet/pages.py", line 31, in <module>
    class AutoExtractItemWebPage(AutoExtractWebPage, ItemPage):
  File "<frozen abc>", line 106, in __new__
    
builtins.TypeError: Cannot create a consistent method resolution
order (MRO) for bases Injectable, Generic

2023-08-07 04:00:05 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/usr/local/lib/python3.11/site-packages/scrapy/crawler.py", line 134, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.11/site-packages/scrapy/crawler.py", line 148, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.11/site-packages/scrapy/core/engine.py", line 98, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
  File "/usr/local/lib/python3.11/site-packages/scrapy/core/downloader/__init__.py", line 97, in __init__
    DownloaderMiddlewareManager.from_crawler(crawler)
  File "/usr/local/lib/python3.11/site-packages/scrapy/middleware.py", line 67, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.11/site-packages/scrapy/middleware.py", line 43, in from_settings
    mwcls = load_object(clspath)
  File "/usr/local/lib/python3.11/site-packages/scrapy/utils/misc.py", line 79, in load_object
    mod = import_module(module)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/scrapy_autoextract/__init__.py", line 2, in <module>
    from .providers import AutoExtractProvider  # noqa: F401
  File "/usr/local/lib/python3.11/site-packages/scrapy_autoextract/providers.py", line 17, in <module>
    from autoextract_poet.page_inputs import (
  File "/usr/local/lib/python3.11/site-packages/autoextract_poet/__init__.py", line 2, in <module>
    from .pages import *
  File "/usr/local/lib/python3.11/site-packages/autoextract_poet/pages.py", line 31, in <module>
    class AutoExtractItemWebPage(AutoExtractWebPage, ItemPage):
  File "<frozen abc>", line 106, in __new__
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Injectable, Generic
```

Seems to me that the relevant part of the error trace is: 

```
class AutoExtractItemWebPage(AutoExtractWebPage, ItemPage):
  File "<frozen abc>", line 106, in __new__
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Injectable, Generic
```

Looks like some problem with the autoextract library class inheritance settings. So because of it being an internal issue (at first sight) im a bit stucked here.

My environment:

> Linux vps-87cd9c3d 5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 
> Distributor ID: Ubuntu
   Description:    Ubuntu 20.04.6 LTS
   Release:        20.04
   Codename:       focal

> Bash version: 5.0.17(1)-release

I use docker compose and this is how mi image is defined:

```
pyprojects:
    container_name: "pyprojects"
    image: python
    restart: unless-stopped
    tty: true
    environment:
      - HOST=0.0.0.0
      - PORT=1420
      - DEV=true
    privileged: true
    entrypoint: /pyprojects/entrypoint.sh
    volumes:
      - ../../data/pyprojects/:/pyprojects
    ports:
      - "1420:1420"
```
Python version:
> Python 3.11.4

Installed libs:

```
scrapy
dataclasses
dataclasses_json
langdetect

# used by autonews
scrapy-autoextract
pymongo
gspread
```

I can imagine that this is something related with my local host or python environment, i've tried the `python:3.10.12` image tag but the problem is still the same.

I hope you can give me some insight about this because i'm probably not the only one facing with this problem, but i can't find any related post (refering to zyte autoextract) browsing google.

I'll be glad to give you any more information you need and discuss the issue if needed.

**Comment by Gallaecio** [comment]
Some zyte-autoextract dependencies have evolved and became incompatible with zyte-autoextract.

As a workaround, the following dependency freezes might help:

```
web-poet==0.9.0
autoextract-poet==0.4.0
```

**Comment by diego-alfadev** [comment]
You mean `scrapy-autoextract` dependencies that became incompatible with `zyte-autoextract`?

Should I move from scrapy-autoextract to zyte-autoextract or set that dependency versions in my requirements.txt straight forward?

**Comment by Gallaecio** [comment]
> Should I move from scrapy-autoextract to zyte-autoextract 

No, sorry for the confusion.

> or set that dependency versions in my requirements.txt straight forward?

This.

In fact, you only need to freeze web-poet (`web-poet==0.9.0`), I have just checked and, as I suspected, autoextract-poet 0.4.0 is the latest version already.

**Comment by diego-alfadev** [comment]
Thanks Gallaecio, after freezing `web-poet` all the process began to work again as expected.

With the provided error message i thought it would be more difficult to identify the problem.

Is this something you have alerady seen in the zyte team? Seems a bit tricky to me that you have to configure such freezes in order to make the lib work, are you guys working on that _or is there something im missing in the trace that blamed this specific dependency incompatibility_?

It will be great to know in order to improve my deep understanding of the library as its part of mi service core.

That being said, thank you so much for the help.

**Comment by Gallaecio** [comment]
Library freezing is a general best practice when working on a Python project (as opposed to a reusable package).

However, what matters here is that zyte-autoextract and scrapy-autoextract should generally not be used anymore for new projects. So existing projects should have frozen dependencies when they installed it, and should not break, and new projects should use [Zyte API automatic extraction](https://docs.zyte.com/zyte-api/usage/extract.html) through [scrapy-zyte-api](https://github.com/scrapy-plugins/scrapy-zyte-api), which is compatible with the latest web-poet.
